compile coffee with webpack and...
- removed normalize.css since it's already present in bootstrap http://getbootstrap.com/css/#overview-normalize
- removed bower config since all dependencies are available in npm

TODO: understand and fix this error when using the source-map option:

```
/Users/daniel/dev/ds/seed/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:161
      if(isError) throw e;
                        ^
Error: "Users/daniel/dev/ds/seed/app/src/index.coffee" is not in the SourceMap.
```